"""Initial migration

Revision ID: 919a915ce050
Revises: 
Create Date: 2026-02-16 01:05:09.612530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '919a915ce050'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grid_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('has_problem_column', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pattern',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('structure_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('grid_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grid_type_id'], ['grid_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('user_schools',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('question_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('question_hash', sa.String(length=64), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('default_marks', sa.Integer(), nullable=True),
    sa.Column('k_level', sa.String(length=20), nullable=True),
    sa.Column('default_unit', sa.Integer(), nullable=True),
    sa.Column('default_section', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_hash'),
    sa.UniqueConstraint('subject_id', 'question_hash', name='uq_subject_question_hash')
    )
    op.create_table('subject_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('batch', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('pattern_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['pattern_id'], ['pattern.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'department_id', 'batch', 'version', name='uq_subject_version')
    )
    op.create_table('question_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_version_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subject_version_id'], ['subject_version.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject_version_pattern',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_version_id', sa.Integer(), nullable=False),
    sa.Column('pattern_id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['pattern_id'], ['pattern.id'], ),
    sa.ForeignKeyConstraint(['subject_version_id'], ['subject_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject_weightage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_version_id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.Integer(), nullable=True),
    sa.Column('sec_a_count', sa.Integer(), nullable=True),
    sa.Column('sec_b_count', sa.Integer(), nullable=True),
    sa.Column('sec_c_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_version_id'], ['subject_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_bank_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_bank_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=1), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('k_level', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_bank_id'], ['question_bank.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_paper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_version_id', sa.Integer(), nullable=False),
    sa.Column('source_question_bank_id', sa.Integer(), nullable=True),
    sa.Column('paper_code', sa.String(length=20), nullable=False),
    sa.Column('paper_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.Integer(), nullable=True),
    sa.Column('last_modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_question_bank_id'], ['question_bank.id'], ),
    sa.ForeignKeyConstraint(['subject_version_id'], ['subject_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_paper_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_paper_id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=1), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('k_level', sa.String(length=20), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('source_question_id', sa.Integer(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('manual_text_override', sa.Text(), nullable=True),
    sa.Column('is_duplicate_flag', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_paper_id'], ['question_paper.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_paper_item')
    op.drop_table('question_paper')
    op.drop_table('question_bank_item')
    op.drop_table('subject_weightage')
    op.drop_table('subject_version_pattern')
    op.drop_table('question_bank')
    op.drop_table('subject_version')
    op.drop_table('question_master')
    op.drop_table('user_schools')
    op.drop_table('subject')
    op.drop_table('department')
    op.drop_table('users')
    op.drop_table('school')
    op.drop_table('pattern')
    op.drop_table('grid_type')
    # ### end Alembic commands ###
